[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "qtile-mutable-scratch"
dynamic = ["version"]
description = "Add mutable scratch functionality to qtile"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
requires-python = ">=3.6"
authors = [
    { name = "James Wright", email = "james@jameswright.xyz" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

[project.urls]
Issues = "https://github.com/jrwrigh/qtile-mutable_scratch/issues"
Homepage = "https://github.com/jrwrigh/qtile-mutable_scratch"

[tool.hatch.version]
path = "qtile_mutable_scratch/_version.py"

[tool.hatch.build.targets.sdist]
include = [
    "/qtile_mutable_scratch",
]

[tool.hatch.build.targets.wheel]
packages = ["qtile_mutable_scratch"]
